question_data =[
        {
        "category": "Science: Computers",
        "type": "boolean", "difficulty": "medium",
        "question": "The first computer bug was formed by faulty wires.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]
    },
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                          "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                          "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The open source program Redis is a relational database server.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                          "question": "AMD created the first consumer 64-bit processor.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                          "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "Actor Tommy Chong served prison time.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},

]

